# Creating a Sentiment Analysis Web App
## Using PyTorch and SageMaker

_Deep Learning Nanodegree Program | Deployment_

---

Now that we have a basic understanding of how SageMaker works we will try to use it to construct a complete project from end to end. Our goal will be to have a simple web page which a user can use to enter a movie review. The web page will then send the review off to our deployed model which will predict the sentiment of the entered review.

## Instructions

Some template code has already been provided for you, and you will need to implement additional functionality to successfully complete this notebook. You will not need to modify the included code beyond what is requested. Sections that begin with '**TODO**' in the header indicate that you need to complete or implement some portion within them. Instructions will be provided for each section and the specifics of the implementation are marked in the code block with a `# TODO: ...` comment. Please be sure to read the instructions carefully!

In addition to implementing code, there will be questions for you to answer which relate to the task and your implementation. Each section where you will answer a question is preceded by a '**Question:**' header. Carefully read each question and provide your answer below the '**Answer:**' header by editing the Markdown cell.

> **Note**: Code and Markdown cells can be executed using the **Shift+Enter** keyboard shortcut. In addition, a cell can be edited by typically clicking it (double-click for Markdown cells) or by pressing **Enter** while it is highlighted.

## General Outline

Recall the general outline for SageMaker projects using a notebook instance.

1. Download or otherwise retrieve the data.
2. Process / Prepare the data.
3. Upload the processed data to S3.
4. Train a chosen model.
5. Test the trained model (typically using a batch transform job).
6. Deploy the trained model.
7. Use the deployed model.

For this project, you will be following the steps in the general outline with some modifications. 

First, you will not be testing the model in its own step. You will still be testing the model, however, you will do it by deploying your model and then using the deployed model by sending the test data to it. One of the reasons for doing this is so that you can make sure that your deployed model is working correctly before moving forward.

In addition, you will deploy and use your trained model a second time. In the second iteration you will customize the way that your trained model is deployed by including some of your own code. In addition, your newly deployed model will be used in the sentiment analysis web app.

## Step 1: Downloading the data

As in the XGBoost in SageMaker notebook, we will be using the [IMDb dataset](http://ai.stanford.edu/~amaas/data/sentiment/)

> Maas, Andrew L., et al. [Learning Word Vectors for Sentiment Analysis](http://ai.stanford.edu/~amaas/data/sentiment/). In _Proceedings of the 49th Annual Meeting of the Association for Computational Linguistics: Human Language Technologies_. Association for Computational Linguistics, 2011.

In [68]:
%mkdir ../data
!wget -O ../data/aclImdb_v1.tar.gz http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz
!tar -zxf ../data/aclImdb_v1.tar.gz -C ../data

mkdir: cannot create directory ‘../data’: File exists
--2020-07-02 15:12:31--  http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz
Resolving ai.stanford.edu (ai.stanford.edu)... 171.64.68.10
Connecting to ai.stanford.edu (ai.stanford.edu)|171.64.68.10|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 84125825 (80M) [application/x-gzip]
Saving to: ‘../data/aclImdb_v1.tar.gz’

../data/aclImdb_v1. 100%[===================>]  80.23M  10.8MB/s    in 10s     

2020-07-02 15:12:41 (7.78 MB/s) - ‘../data/aclImdb_v1.tar.gz’ saved [84125825/84125825]



## Step 2: Preparing and Processing the data

Also, as in the XGBoost notebook, we will be doing some initial data processing. The first few steps are the same as in the XGBoost example. To begin with, we will read in each of the reviews and combine them into a single input structure. Then, we will split the dataset into a training set and a testing set.

In [69]:
import os
import glob

def read_imdb_data(data_dir='../data/aclImdb'):
    data = {}
    labels = {}
    
    for data_type in ['train', 'test']:
        data[data_type] = {}
        labels[data_type] = {}
        
        for sentiment in ['pos', 'neg']:
            data[data_type][sentiment] = []
            labels[data_type][sentiment] = []
            
            path = os.path.join(data_dir, data_type, sentiment, '*.txt')
            files = glob.glob(path)
            
            for f in files:
                with open(f) as review:
                    data[data_type][sentiment].append(review.read())
                    # Here we represent a positive review by '1' and a negative review by '0'
                    labels[data_type][sentiment].append(1 if sentiment == 'pos' else 0)
                    
            assert len(data[data_type][sentiment]) == len(labels[data_type][sentiment]), \
                    "{}/{} data size does not match labels size".format(data_type, sentiment)
                
    return data, labels

In [70]:
data, labels = read_imdb_data()
print("IMDB reviews: train = {} pos / {} neg, test = {} pos / {} neg".format(
            len(data['train']['pos']), len(data['train']['neg']),
            len(data['test']['pos']), len(data['test']['neg'])))

IMDB reviews: train = 12500 pos / 12500 neg, test = 12500 pos / 12500 neg


Now that we've read the raw training and testing data from the downloaded dataset, we will combine the positive and negative reviews and shuffle the resulting records.

In [71]:
from sklearn.utils import shuffle

def prepare_imdb_data(data, labels):
    """Prepare training and test sets from IMDb movie reviews."""
    
    #Combine positive and negative reviews and labels
    data_train = data['train']['pos'] + data['train']['neg']
    data_test = data['test']['pos'] + data['test']['neg']
    labels_train = labels['train']['pos'] + labels['train']['neg']
    labels_test = labels['test']['pos'] + labels['test']['neg']
    
    #Shuffle reviews and corresponding labels within training and test sets
    data_train, labels_train = shuffle(data_train, labels_train)
    data_test, labels_test = shuffle(data_test, labels_test)
    
    # Return a unified training data, test data, training labels, test labets
    return data_train, data_test, labels_train, labels_test

In [72]:
train_X, test_X, train_y, test_y = prepare_imdb_data(data, labels)
print("IMDb reviews (combined): train = {}, test = {}".format(len(train_X), len(test_X)))

IMDb reviews (combined): train = 25000, test = 25000


Now that we have our training and testing sets unified and prepared, we should do a quick check and see an example of the data our model will be trained on. This is generally a good idea as it allows you to see how each of the further processing steps affects the reviews and it also ensures that the data has been loaded correctly.

In [73]:
print(train_X[100])
print(train_y[100])

OK, so the FX are not high budget. But this story is based on actual events. Not something thrown together to make a couple of rich actors, even richer!! As most movies that are based on books, there are somethings that just don't fit. Only a couple of people have stated that this movie was based on real events, not a knock-off as most people believe it is!! This movie is in no way related too TWISTER! Other than both movies are about tornadoes.<br /><br />For those of you who have problems with the science of the tornadoes and storms in the movie, there are a couple of things you need to remember... The actual "night of the twisters" was June 3, 1980. So this movie was released 16 years after the actual events. Try think how far storm research has advanced in that time. It happened in a larger town; Grand Island, Nebraska is the third largest city in the state. Even though the movie calls the town something else, and says it's a small town. For the real story check out: http://www.git

The first step in processing the reviews is to make sure that any html tags that appear should be removed. In addition we wish to tokenize our input, that way words such as *entertained* and *entertaining* are considered the same with regard to sentiment analysis.

In [74]:
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import *

import re
from bs4 import BeautifulSoup

def review_to_words(review):
    nltk.download("stopwords", quiet=True)
    stemmer = PorterStemmer()
    
    text = BeautifulSoup(review, "html.parser").get_text() # Remove HTML tags
    text = re.sub(r"[^a-zA-Z0-9]", " ", text.lower()) # Convert to lower case
    words = text.split() # Split string into words
    words = [w for w in words if w not in stopwords.words("english")] # Remove stopwords
    words = [PorterStemmer().stem(w) for w in words] # stem
    
    return words

The `review_to_words` method defined above uses `BeautifulSoup` to remove any html tags that appear and uses the `nltk` package to tokenize the reviews. As a check to ensure we know how everything is working, try applying `review_to_words` to one of the reviews in the training set.

In [76]:
# TODO: Apply review_to_words to a review (train_X[100] or any other review)
review_to_words(train_X[100])

['ok',
 'fx',
 'high',
 'budget',
 'stori',
 'base',
 'actual',
 'event',
 'someth',
 'thrown',
 'togeth',
 'make',
 'coupl',
 'rich',
 'actor',
 'even',
 'richer',
 'movi',
 'base',
 'book',
 'someth',
 'fit',
 'coupl',
 'peopl',
 'state',
 'movi',
 'base',
 'real',
 'event',
 'knock',
 'peopl',
 'believ',
 'movi',
 'way',
 'relat',
 'twister',
 'movi',
 'tornado',
 'problem',
 'scienc',
 'tornado',
 'storm',
 'movi',
 'coupl',
 'thing',
 'need',
 'rememb',
 'actual',
 'night',
 'twister',
 'june',
 '3',
 '1980',
 'movi',
 'releas',
 '16',
 'year',
 'actual',
 'event',
 'tri',
 'think',
 'far',
 'storm',
 'research',
 'advanc',
 'time',
 'happen',
 'larger',
 'town',
 'grand',
 'island',
 'nebraska',
 'third',
 'largest',
 'citi',
 'state',
 'even',
 'though',
 'movi',
 'call',
 'town',
 'someth',
 'els',
 'say',
 'small',
 'town',
 'real',
 'stori',
 'check',
 'http',
 'www',
 'gitwist',
 'com']

**Question:** Above we mentioned that `review_to_words` method removes html formatting and allows us to tokenize the words found in a review, for example, converting *entertained* and *entertaining* into *entertain* so that they are treated as though they are the same word. What else, if anything, does this method do to the input?

**Answer:**

- made lower case
- removed all the common words that do not contribute much to the semantic eg 'the', 'a', 'over'
- removed punctuation

The method below applies the `review_to_words` method to each of the reviews in the training and testing datasets. In addition it caches the results. This is because performing this processing step can take a long time. This way if you are unable to complete the notebook in the current session, you can come back without needing to process the data a second time.

In [136]:
import pickle

cache_dir = os.path.join("../cache", "sentiment_analysis")  # where to store cache files
os.makedirs(cache_dir, exist_ok=True)  # ensure cache directory exists

def preprocess_data(data_train, data_test, labels_train, labels_test,
                    cache_dir=cache_dir, cache_file="preprocessed_data.pkl"):
    """Convert each review to words; read from cache if available."""

    # If cache_file is not None, try to read from it first
    cache_data = None
    if cache_file is not None:
        try:
            with open(os.path.join(cache_dir, cache_file), "rb") as f:
                cache_data = pickle.load(f)
            print("Read preprocessed data from cache file:", cache_file)
        except:
            pass  # unable to read from cache, but that's okay
    
    # If cache is missing, then do the heavy lifting
    if cache_data is None:
        # Preprocess training and test data to obtain words for each review
        #words_train = list(map(review_to_words, data_train))
        #words_test = list(map(review_to_words, data_test))
        words_train = [review_to_words(review) for review in data_train]
        words_test = [review_to_words(review) for review in data_test]
        
        # Write to cache file for future runs
        if cache_file is not None:
            cache_data = dict(words_train=words_train, words_test=words_test,
                              labels_train=labels_train, labels_test=labels_test)
            with open(os.path.join(cache_dir, cache_file), "wb") as f:
                pickle.dump(cache_data, f)
            print("Wrote preprocessed data to cache file:", cache_file)
    else:
        # Unpack data loaded from cache file
        words_train, words_test, labels_train, labels_test = (cache_data['words_train'],
                cache_data['words_test'], cache_data['labels_train'], cache_data['labels_test'])
    
    return words_train, words_test, labels_train, labels_test

In [168]:
# Preprocess data
train_X, test_X, train_y, test_y = preprocess_data(train_X, test_X, train_y, test_y)

Read preprocessed data from cache file: preprocessed_data.pkl


## Transform the data

In the XGBoost notebook we transformed the data from its word representation to a bag-of-words feature representation. For the model we are going to construct in this notebook we will construct a feature representation which is very similar. To start, we will represent each word as an integer. Of course, some of the words that appear in the reviews occur very infrequently and so likely don't contain much information for the purposes of sentiment analysis. The way we will deal with this problem is that we will fix the size of our working vocabulary and we will only include the words that appear most frequently. We will then combine all of the infrequent words into a single category and, in our case, we will label it as `1`.

Since we will be using a recurrent neural network, it will be convenient if the length of each review is the same. To do this, we will fix a size for our reviews and then pad short reviews with the category 'no word' (which we will label `0`) and truncate long reviews.

### (TODO) Create a word dictionary

To begin with, we need to construct a way to map words that appear in the reviews to integers. Here we fix the size of our vocabulary (including the 'no word' and 'infrequent' categories) to be `5000` but you may wish to change this to see how it affects the model.

> **TODO:** Complete the implementation for the `build_dict()` method below. Note that even though the vocab_size is set to `5000`, we only want to construct a mapping for the most frequently appearing `4998` words. This is because we want to reserve the special labels `0` for 'no word' and `1` for 'infrequent word'.

In [169]:
import numpy as np
from collections import Counter

def build_dict(data, vocab_size = 5000):
    """Construct and return a dictionary mapping each of the most frequently appearing words to a unique integer."""
    
    # TODO: Determine how often each word appears in `data`. Note that `data` is a list of sentences and that a
    #       sentence is a list of words.
    
    word_count = Counter()
    for review in data:
        word_count.update(review)
    
    # TODO: Sort the words found in `data` so that sorted_words[0] is the most frequently appearing word and
    #       sorted_words[-1] is the least frequently appearing word.
    
    sorted_words = sorted(word_count, key=word_count.get, reverse=True)
    
    word_dict = {} # This is what we are building, a dictionary that translates words into integers
    for idx, word in enumerate(sorted_words[:vocab_size - 2]): # The -2 is so that we save room for the 'no word'
        word_dict[word] = idx + 2                              # 'infrequent' labels
        
    return word_dict


In [170]:
word_dict = build_dict(train_X)

**Question:** What are the five most frequently appearing (tokenized) words in the training set? Does it makes sense that these words appear frequently in the training set?

**Answer:**

In [171]:
# TODO: Use this space to determine the five most frequently appearing words in the training set.

print(list(word_dict.keys())[:5])


['movi', 'film', 'one', 'like', 'time']


### Save `word_dict`

Later on when we construct an endpoint which processes a submitted review we will need to make use of the `word_dict` which we have created. As such, we will save it to a file now for future use.

In [172]:
data_dir = '../data/pytorch' # The folder we will use for storing data
if not os.path.exists(data_dir): # Make sure that the folder exists
    os.makedirs(data_dir)

In [173]:
with open(os.path.join(data_dir, 'word_dict.pkl'), "wb") as f:
    pickle.dump(word_dict, f)

### Transform the reviews

Now that we have our word dictionary which allows us to transform the words appearing in the reviews into integers, it is time to make use of it and convert our reviews to their integer sequence representation, making sure to pad or truncate to a fixed length, which in our case is `500`.

In [174]:
def convert_and_pad(word_dict, sentence, pad=500):
    NOWORD = 0 # We will use 0 to represent the 'no word' category
    INFREQ = 1 # and we use 1 to represent the infrequent words, i.e., words not appearing in word_dict
    
    working_sentence = [NOWORD] * pad
    
    for word_index, word in enumerate(sentence[:pad]):
        if word in word_dict:
            working_sentence[word_index] = word_dict[word]
        else:
            working_sentence[word_index] = INFREQ
            
    return working_sentence, min(len(sentence), pad)


def convert_and_pad_data(word_dict, data, pad=500):
    result = []
    lengths = []
    
    for sentence in data:
        converted, leng = convert_and_pad(word_dict, sentence, pad)
        result.append(converted)
        lengths.append(leng)
        
    return np.array(result), np.array(lengths)

In [175]:
train_X, train_X_len = convert_and_pad_data(word_dict, train_X)
test_X, test_X_len = convert_and_pad_data(word_dict, test_X)

As a quick check to make sure that things are working as intended, check to see what one of the reviews in the training set looks like after having been processeed. Does this look reasonable? What is the length of a review in the training set?

In [176]:
# Use this cell to examine one of the processed reviews to make sure everything is working as intended.
print(train_X[0])
print(train_X_len)

[ 258    7    2 2124   22   32 1865    9    1  127  187    5   41  188
  634   25  109   59  452  467  259  266    2  115   61   45   22   36
   52 1109 2491  203   39    5 1496  124  308   54   48    1  117 1539
 1412 1469  109    1  334    1   37  262 1333  203    4 4436  266   35
   37  203  531  203 2143  401   11    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0 

**Question:** In the cells above we use the `preprocess_data` and `convert_and_pad_data` methods to process both the training and testing set. Why or why not might this be a problem?

**Answer:**

- Very large sized reviews may yield less accuracy
- With punctuation removed, there may be a minor accuracy decrease eg "Amazing??" and "Amazing!!!"

In [178]:
print(train_X_len)

[ 63 408 191 ...  92  63 183]


## Step 3: Upload the data to S3

As in the XGBoost notebook, we will need to upload the training dataset to S3 in order for our training code to access it. For now we will save it locally and we will upload to S3 later on.

### Save the processed training dataset locally

It is important to note the format of the data that we are saving as we will need to know it when we write the training code. In our case, each row of the dataset has the form `label`, `length`, `review[500]` where `review[500]` is a sequence of `500` integers representing the words in the review.

In [179]:
import pandas as pd
    
pd.concat([pd.DataFrame(train_y), pd.DataFrame(train_X_len), pd.DataFrame(train_X)], axis=1) \
        .to_csv(os.path.join(data_dir, 'train.csv'), header=False, index=False)

### Uploading the training data


Next, we need to upload the training data to the SageMaker default S3 bucket so that we can provide access to it while training our model.

In [180]:
import sagemaker

sagemaker_session = sagemaker.Session()

bucket = sagemaker_session.default_bucket()
prefix = 'sagemaker/sentiment_rnn'

role = sagemaker.get_execution_role()

In [181]:
input_data = sagemaker_session.upload_data(path=data_dir, bucket=bucket, key_prefix=prefix)

**NOTE:** The cell above uploads the entire contents of our data directory. This includes the `word_dict.pkl` file. This is fortunate as we will need this later on when we create an endpoint that accepts an arbitrary review. For now, we will just take note of the fact that it resides in the data directory (and so also in the S3 training bucket) and that we will need to make sure it gets saved in the model directory.

## Step 4: Build and Train the PyTorch Model

In the XGBoost notebook we discussed what a model is in the SageMaker framework. In particular, a model comprises three objects

 - Model Artifacts,
 - Training Code, and
 - Inference Code,
 
each of which interact with one another. In the XGBoost example we used training and inference code that was provided by Amazon. Here we will still be using containers provided by Amazon with the added benefit of being able to include our own custom code.

We will start by implementing our own neural network in PyTorch along with a training script. For the purposes of this project we have provided the necessary model object in the `model.py` file, inside of the `train` folder. You can see the provided implementation by running the cell below.

In [182]:
!pygmentize train/model.py

import torch.nn as nn

class LSTMClassifier(nn.Module):
    """
    This is the simple RNN model we will be using to perform Sentiment Analysis.
    """

    def __init__(self, embedding_dim, hidden_dim, vocab_size):
        """
        Initialize the model by settingg up the various layers.
        """
        super(LSTMClassifier, self).__init__()

        self.embedding = nn.Embedding(vocab_size, embedding_dim, padding_idx=0)
        self.lstm = nn.LSTM(embedding_dim, hidden_dim)
        self.dense = nn.Linear(in_features=hidden_dim, out_features=1)
        self.sig = nn.Sigmoid()
        
        self.word_dict = None

    def forward(self, x):
        """ Perform a forward pass of our model on some input. """
        x = x.t()
        lengths = x[0,:]
        print(lengths.shape)
        print(lengths)
        print('lol')

        reviews = x[1:,:]
        embeds = self.embedding(reviews)
        lstm_out, _ = self.lstm(embeds)
        # lstm_out torch.Size([500, 50, 100])    seq

The important takeaway from the implementation provided is that there are three parameters that we may wish to tweak to improve the performance of our model. These are the embedding dimension, the hidden dimension and the size of the vocabulary. We will likely want to make these parameters configurable in the training script so that if we wish to modify them we do not need to modify the script itself. We will see how to do this later on. To start we will write some of the training code in the notebook so that we can more easily diagnose any issues that arise.

First we will load a small portion of the training data set to use as a sample. It would be very time consuming to try and train the model completely in the notebook as we do not have access to a gpu and the compute instance that we are using is not particularly powerful. However, we can work on a small bit of the data to get a feel for how our training script is behaving.

In [183]:
import torch
import torch.utils.data

# Read in only the first 250 rows
train_sample = pd.read_csv(os.path.join(data_dir, 'train.csv'), header=None, names=None, nrows=250)

# Turn the input pandas dataframe into tensors
train_sample_y = torch.from_numpy(train_sample[[0]].values).float().squeeze()
train_sample_X = torch.from_numpy(train_sample.drop([0], axis=1).values).long()

# Build the dataset
train_sample_ds = torch.utils.data.TensorDataset(train_sample_X, train_sample_y)
# Build the dataloader
train_sample_dl = torch.utils.data.DataLoader(train_sample_ds, batch_size=50)

### (TODO) Writing the training method

Next we need to write the training code itself. This should be very similar to training methods that you have written before to train PyTorch models. We will leave any difficult aspects such as model saving / loading and parameter loading until a little later.

In [184]:
import torch.nn as nn

def train(model, train_loader, epochs, optimizer, loss_fn, device):
    for epoch in range(1, epochs + 1):
        model.train()
        total_loss = 0
        for batch in train_loader:         
            batch_X, batch_y = batch
            
            batch_X = batch_X.to(device)
            batch_y = batch_y.to(device)
            
            # TODO: Complete this train method to train the model provided.
            optimizer.zero_grad()
            out = model.forward(batch_X)
            loss = loss_fn(out, batch_y)
            loss.backward()
            
            #nn.utils.clip_grad_norm_(model.parameters(), clip=5)

            optimizer.step()
            
            total_loss += loss.data.item()
        print("Epoch: {}, BCELoss: {}".format(epoch, total_loss / len(train_loader)))

Supposing we have the training method above, we will test that it is working by writing a bit of code in the notebook that executes our training method on the small sample training set that we loaded earlier. The reason for doing this in the notebook is so that we have an opportunity to fix any errors that arise early when they are easier to diagnose.

In [185]:
import torch.optim as optim
from train.model import LSTMClassifier

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = LSTMClassifier(32, 100, 5000).to(device)
optimizer = optim.Adam(model.parameters())
loss_fn = torch.nn.BCELoss()

train(model, train_sample_dl, 5, optimizer, loss_fn, device)

torch.Size([50])
tensor([ 63, 408, 191, 185,  86,  55, 133, 133,  91,  32,  65, 110,  70,  45,
         49,  95,  71,  69,  78, 126, 107, 103, 115,  72, 133, 119, 270, 438,
         59,  67, 157,  63,  58, 172, 108,  46,  80,  98,  78,  91, 411, 109,
         73,  90, 138,  23, 307,  79, 126,  24])
lol
torch.Size([50])
tensor([ 67,  94, 311,  72,  54,  80, 173,  51,  57, 330,  63,  58,  69,  67,
        267, 108,  66, 153, 178, 113, 114, 156, 244,  72,  75,  79,  29,  72,
        157,  48, 184, 297,  95,  37, 173, 126,  58, 127, 500, 124, 164, 437,
        270,  73, 131,  89,  62,  37,  73,  28])
lol
torch.Size([50])
tensor([173,  83,  30,  71, 104,  44,  23,  64,  94,  82,  77,  82,  54,  53,
         68,  89, 255,  81,  66,  96,  80,  60,  74, 179, 167,  69,  64, 101,
         41,  79, 427, 148, 346,  76, 207,  85, 320,  88,  91,  82,  72, 135,
        259,  93, 108, 171,  61,  72,  64,  58])
lol
torch.Size([50])
tensor([101,  79, 155, 137, 333, 179,  97, 382, 123, 316,  73, 204, 191

In order to construct a PyTorch model using SageMaker we must provide SageMaker with a training script. We may optionally include a directory which will be copied to the container and from which our training code will be run. When the training container is executed it will check the uploaded directory (if there is one) for a `requirements.txt` file and install any required Python libraries, after which the training script will be run.

### (TODO) Training the model

When a PyTorch model is constructed in SageMaker, an entry point must be specified. This is the Python file which will be executed when the model is trained. Inside of the `train` directory is a file called `train.py` which has been provided and which contains most of the necessary code to train our model. The only thing that is missing is the implementation of the `train()` method which you wrote earlier in this notebook.

**TODO**: Copy the `train()` method written above and paste it into the `train/train.py` file where required.

The way that SageMaker passes hyperparameters to the training script is by way of arguments. These arguments can then be parsed and used in the training script. To see how this is done take a look at the provided `train/train.py` file.

In [186]:
from sagemaker.pytorch import PyTorch

estimator = PyTorch(entry_point="train.py",
                    source_dir="train",
                    role=role,
                    framework_version='0.4.0',
                    train_instance_count=1,
                    train_instance_type='ml.p2.xlarge',
                    hyperparameters={
                        'epochs': 10,
                        'hidden_dim': 200,
                    })

In [187]:
estimator.fit({'training': input_data})

'create_image_uri' will be deprecated in favor of 'ImageURIProvider' class in SageMaker Python SDK v2.
's3_input' class will be renamed to 'TrainingInput' in SageMaker Python SDK v2.
'create_image_uri' will be deprecated in favor of 'ImageURIProvider' class in SageMaker Python SDK v2.


2020-07-02 16:44:41 Starting - Starting the training job...
2020-07-02 16:44:43 Starting - Launching requested ML instances......
2020-07-02 16:45:51 Starting - Preparing the instances for training......
2020-07-02 16:47:06 Downloading - Downloading input data......
2020-07-02 16:48:12 Training - Training image download completed. Training in progress..bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
2020-07-02 16:48:13,041 sagemaker-containers INFO     Imported framework sagemaker_pytorch_container.training
2020-07-02 16:48:13,072 sagemaker_pytorch_container.training INFO     Block until all host DNS lookups succeed.
2020-07-02 16:48:14,486 sagemaker_pytorch_container.training INFO     Invoking user training script.
2020-07-02 16:48:14,709 sagemaker-containers INFO     Module train does not provide a setup.py. 
Generating setup.py
2020-07-02 16:48:14,710 sagemaker-containers INFO     Generating setup.cfg
2020-07-02 16:48:1

torch.Size([512])
tensor([  48,   66,  160,   86,   99,  123,   91,   72,   89,   89,
          86,  131,   98,  105,   32,  137,   79,   79,   60,   81,
          46,  212,   61,  129,   87,   68,   52,   39,  134,   34,
          91,   23,   66,  375,   77,  184,   65,  202,  180,  120,
         170,  182,   35,  190,  101,  107,   59,   57,   61,   98,
         143,   24,   55,   37,   99,   54,  129,  103,  157,   51,
          95,  263,   57,  154,   60,   47,   83,   78,   69,  321,
          92,   76,   80,  160,   74,  120,   71,   73,   27,   58,
          69,  146,  190,   72,  176,  437,   52,   66,   54,   59,
          63,   25,   50,   58,  102,   22,  187,   67,   79,  131,
         170,  165,  119,  307,   64,   70,  219,  100,  215,  220,
          96,  142,  461,   72,   52,  107,   25,  156,  116,  401,
          31,  268,   68,  157,   58,   64,  126,  435,  114,  106,
          89,   89,   58,  176,   34,  103,   22,   58,  293,   87,
         119,   78,   40,  204

torch.Size([512])
tensor([ 294,  141,   39,   83,   67,   77,   91,  133,   93,   63,
          98,   75,   23,   81,   84,   74,  139,  146,   74,   84,
          96,  126,  167,  147,   41,   45,   63,  117,   22,  214,
         142,  217,  263,  271,   80,  127,   69,   94,   89,   56,
         313,   94,   64,  270,   31,   49,  187,  109,   69,   40,
         102,  107,   66,  120,   60,  153,  189,  377,   29,   67,
         131,  139,   59,   54,  103,   82,   37,  254,   44,  218,
          83,   93,   77,  316,   13,   44,  132,   51,   17,   41,
          68,   63,  132,   84,   67,  128,   64,  185,  207,  151,
         220,  118,   78,   77,  301,   85,   82,  201,  137,   70,
          66,   29,   86,   83,   81,   53,  107,  174,  150,   96,
          54,   70,  127,   62,  207,   70,  125,  125,   34,  277,
         233,  205,  272,  120,  142,  251,   63,   94,   93,  257,
         155,  174,   72,   74,  206,   84,  354,   72,   21,   71,
          92,  165,   45,  117

torch.Size([512])
tensor([ 157,   45,  250,   77,   79,  117,   77,   52,  111,   80,
          73,  122,   29,   75,  131,  311,   96,   67,  123,   36,
          69,  211,   14,  109,   47,   23,   24,  134,   71,  291,
         145,   88,   69,   76,   82,  102,  101,   63,  113,   60,
          90,   87,   31,  278,  218,  111,   18,  126,   68,  303,
          22,  444,   73,  100,   51,   62,  152,   89,   95,  309,
          58,  148,   56,   62,  130,  221,  120,  107,  133,  263,
          69,   41,  170,  195,   57,  248,   84,  500,   57,  166,
         113,  121,  136,  308,   86,   44,   63,  285,   63,  317,
          68,   32,  260,   23,  121,   21,   78,  113,   86,  164,
         322,  427,  222,  110,   82,   51,   80,   22,   50,   73,
          34,   60,   73,  215,  187,  107,   84,  102,  132,  204,
          94,  104,   72,   52,   76,  159,  117,  184,   56,   65,
          96,  103,   83,  241,   40,  155,  424,  238,  110,  103,
          70,   93,   55,  228

torch.Size([424])
tensor([  48,   76,  473,  130,  435,  206,   76,  202,   91,   55,
          74,   85,  390,  333,  109,  130,  180,  172,   76,  120,
         129,   66,   23,  196,   37,  110,   37,  122,  134,   85,
          55,  126,   55,  160,  137,   57,  188,  124,   60,   62,
          85,  122,  120,   84,  281,   26,   62,  174,   64,   52,
          94,   58,   40,  172,  100,   71,  337,  193,   27,   95,
          60,   63,   76,  107,   90,   86,   62,   68,  142,   69,
         348,  394,   53,   65,  115,   93,   30,   67,  256,   43,
          63,  266,   49,  102,   83,   58,  129,  495,   64,  111,
          85,  112,  109,   73,  115,   61,   62,   33,  152,  176,
          44,   71,  104,  182,   61,   92,  197,  220,   41,  150,
          58,  286,  379,   80,  101,   70,  249,   72,  173,  104,
         179,  207,  500,  108,   73,  253,  348,   53,   73,  223,
          62,   61,   99,  270,  116,   76,  278,  181,  245,   86,
         327,   76,   74,  254

torch.Size([512])
tensor([  51,   56,   54,   61,  230,   51,  177,  231,  401,   15,
         136,   84,   63,   97,  261,   56,   46,  116,  100,   73,
          72,  192,  150,   78,   87,  104,   84,   73,   72,  192,
          74,   51,  353,  170,   59,   61,   73,   99,  178,  373,
         356,  483,  263,  244,   33,   69,  265,  205,   63,  164,
          64,   59,   45,   53,   65,   24,   27,   55,  280,   75,
         145,   75,   63,  308,   66,   25,  261,  102,  116,   70,
         115,   38,  179,  114,   79,  175,  174,   77,  234,  500,
          59,  124,  221,   74,   43,  221,   37,   90,   87,  123,
         105,  240,  194,   59,   95,   39,   48,   52,   81,  108,
          91,   42,   87,  251,   63,   75,   94,  104,  175,   84,
          65,  242,  468,   57,   55,   78,   81,   84,  233,  234,
          40,   49,   67,   68,  229,   66,   74,  313,  133,  107,
         184,  115,   69,  105,   60,  151,   77,  118,   55,  161,
         287,   83,   99,  102

torch.Size([512])
tensor([ 272,   46,   44,   71,   31,  152,   86,  136,  168,  104,
         123,   77,   67,  173,   85,  123,  106,   64,  307,  135,
         111,   67,   61,   47,   71,   33,   59,  219,  101,   21,
          62,   24,   62,   78,   89,   52,   31,  251,   56,   88,
         121,   32,   78,   80,   57,  351,   80,   70,   59,   81,
          89,   65,   23,  385,   55,  112,  174,  137,  120,   89,
         129,  317,  223,   88,  345,  109,   65,  375,   47,   90,
         183,   64,  116,  203,  111,  189,  400,   76,   96,   73,
         414,  105,  189,  226,   65,  126,   65,  283,  116,   54,
         267,   66,   93,   82,   71,   79,  144,  436,   35,  114,
          70,   57,   20,   75,  177,  141,  118,   84,  123,   48,
         304,   49,   83,   61,   52,  123,   66,   80,   71,  329,
          95,   70,   30,   64,   99,   79,  158,   80,   17,   61,
         204,  192,  130,   78,  150,  173,  109,   72,   85,  178,
          85,   39,   78,   51

torch.Size([512])
tensor([  98,   93,  118,   65,  322,   94,   55,  117,  160,  109,
         190,   58,   62,  174,  118,  130,  100,   43,  110,   98,
          41,   93,  105,  166,   68,  111,   51,   29,  129,   73,
          60,   89,  110,  156,   58,   71,   58,   77,   56,   66,
         163,  136,   81,   89,  140,  118,   75,   63,   30,   82,
         466,   72,  163,   78,   73,   48,  106,  257,  207,  278,
          55,   51,   66,   64,  153,  126,  123,  139,  129,   84,
          75,   51,  169,  147,   78,  119,   64,   46,  131,   29,
          64,   73,  105,  142,   56,   76,  175,  106,  200,  426,
          64,  237,  133,   77,   85,   58,  213,   73,   74,  118,
          57,   82,  222,   69,   82,   94,  171,   59,  365,   61,
          69,  131,   80,  291,   70,   69,   59,   75,  222,   89,
          60,   74,  129,   97,   96,   50,   92,   81,  158,  204,
          55,  119,   83,  124,   45,  152,   82,   44,  135,  288,
          31,  124,  103,   94

torch.Size([512])
tensor([ 136,   94,  246,   82,   47,  156,  142,   64,  105,  344,
         208,  189,   54,   40,  114,  478,  103,  112,  500,   60,
          63,  125,  103,   22,   47,   84,   76,  272,  104,  184,
         353,   83,   34,  162,   90,   93,   54,   67,  165,  280,
          89,  115,   30,   65,  205,   26,   53,  433,   51,   61,
         142,  222,   31,  437,   41,  151,   77,   73,   70,   53,
         155,   82,  123,   55,  165,   88,   88,  185,  235,   63,
          95,   86,   81,  171,   83,   94,   59,  116,  209,   55,
         154,   73,   77,   63,  155,   23,  500,  131,  249,  441,
          30,  172,   29,   48,   66,   79,  114,   60,  106,  116,
         132,  423,  213,  275,   66,  288,   75,  153,   27,  138,
          47,   92,  106,   59,  102,  176,   74,  122,   61,  142,
          64,   59,   99,   56,   86,   40,   80,   40,  163,  102,
         139,   94,  349,   85,  256,   51,  179,  128,  167,   61,
          59,   72,   71,  129

torch.Size([512])
tensor([ 111,   49,   87,  103,  220,   70,  186,   49,  182,  237,
          79,  117,   66,  401,  128,   63,  349,  212,   71,   62,
          36,  412,  201,   94,  141,  152,   64,   52,   76,   78,
         303,  104,   44,   17,   52,  121,   33,   73,   61,  112,
          59,  418,  155,   66,   44,   66,  225,  122,   58,  154,
         157,  107,  173,   79,  120,  170,   71,  123,  100,  116,
         241,   65,   67,  143,  143,   61,  288,   62,  102,  348,
          28,   82,  113,   95,   74,  190,   91,  233,  397,   81,
          72,   76,  291,  126,  297,  207,   68,   67,  113,   70,
          64,  243,   79,   79,   63,   91,  104,   74,   82,  185,
          89,  172,   72,  103,   99,   91,   90,   22,   25,   58,
         155,  175,  240,  120,  254,  139,  118,   31,   64,   24,
         251,  353,  193,   48,   33,  500,  155,   64,  125,   62,
         233,   69,   88,   65,   50,  237,  183,   47,   75,  112,
          49,   64,   79,  223

torch.Size([512])
tensor([ 145,   72,  174,  143,   80,   22,   57,   64,   60,   86,
          79,  251,   80,   67,  111,  303,  135,   62,   63,  218,
          75,  120,   77,  244,  103,  100,  104,   66,   45,  149,
          83,   76,  230,  114,   59,  170,  285,  304,  189,  154,
         142,   52,   62,   57,   55,   41,  182,  377,   71,   61,
         423,   31,  139,   89,  187,   62,   79,  310,   38,  173,
          68,   80,  154,  279,  100,  144,   55,  107,   83,   97,
          79,  153,   49,   62,  253,  157,   16,   63,   88,  120,
          73,   69,  106,  101,  254,   16,   56,   82,   77,   55,
          72,   73,  129,  149,  242,  257,   64,   38,  187,   63,
         187,  126,   89,  137,   96,   26,   61,   31,  287,   85,
          53,   69,  163,   34,  145,  418,  500,  135,   29,  167,
          87,   74,   60,   71,   19,   70,  132,   58,   58,  429,
         107,  179,   47,  127,   61,  242,  175,   28,   84,   59,
          83,   88,   84,   42

torch.Size([512])
tensor([ 136,   94,  246,   82,   47,  156,  142,   64,  105,  344,
         208,  189,   54,   40,  114,  478,  103,  112,  500,   60,
          63,  125,  103,   22,   47,   84,   76,  272,  104,  184,
         353,   83,   34,  162,   90,   93,   54,   67,  165,  280,
          89,  115,   30,   65,  205,   26,   53,  433,   51,   61,
         142,  222,   31,  437,   41,  151,   77,   73,   70,   53,
         155,   82,  123,   55,  165,   88,   88,  185,  235,   63,
          95,   86,   81,  171,   83,   94,   59,  116,  209,   55,
         154,   73,   77,   63,  155,   23,  500,  131,  249,  441,
          30,  172,   29,   48,   66,   79,  114,   60,  106,  116,
         132,  423,  213,  275,   66,  288,   75,  153,   27,  138,
          47,   92,  106,   59,  102,  176,   74,  122,   61,  142,
          64,   59,   99,   56,   86,   40,   80,   40,  163,  102,
         139,   94,  349,   85,  256,   51,  179,  128,  167,   61,
          59,   72,   71,  129

torch.Size([512])
tensor([  84,   67,  133,  335,   18,   29,  109,   59,   45,  112,
         154,   91,   81,  160,   95,  204,   94,  134,   81,   79,
          80,  173,   72,   60,  132,   82,   39,   54,  179,  125,
          85,   32,  151,   72,  500,   35,   56,  115,  158,   44,
          33,  299,  249,   76,   45,   63,   90,   79,   61,   49,
          84,   85,  431,  125,   95,  127,  129,  109,  102,   63,
          61,  166,  119,   78,  258,  262,   64,  252,   19,   57,
         110,   32,   67,   86,   43,   77,   59,   45,  123,  241,
         120,  116,   60,   78,   56,  423,   85,  189,  107,   30,
          75,  230,   64,   61,   55,   38,   74,   79,  103,  105,
         155,  149,   63,  150,   84,   58,   65,   19,   71,  139,
          81,  102,   35,   63,   56,   94,   49,   83,   94,  135,
          54,   67,   90,   63,   91,  176,  182,   63,  128,  106,
         178,  211,  202,   62,  171,   73,   99,   84,  381,   83,
          29,   57,  186,   73

torch.Size([512])
tensor([ 312,  193,   99,  403,   68,   47,  264,   70,  192,  208,
          54,  240,   89,   54,  273,   52,  180,   37,   82,  185,
         187,  319,   31,   96,  106,   55,   33,   77,  119,   89,
         140,   52,   89,   97,   34,   41,   96,  160,   71,   92,
          71,  273,   88,   58,  236,   55,   82,  447,   87,   56,
          74,  105,   77,   63,  209,   84,   94,  107,   70,   60,
         387,  183,  173,  119,   58,   62,   62,   93,   73,  400,
          73,  145,   62,  165,  155,  100,   93,   70,   90,   77,
         110,   51,  160,   69,   51,   98,   56,  344,  484,   80,
          31,   32,   87,   70,  248,  121,   77,  113,   98,  200,
          66,   81,  117,  120,   64,  119,   78,  114,   74,   86,
          73,   39,  201,   53,   79,   56,  297,   22,  248,  145,
          20,   99,  424,   22,   74,   29,  414,  218,   58,   57,
         113,  170,  210,   60,  104,   89,   73,  190,   71,   61,
          75,   79,  116,   63

torch.Size([512])
tensor([ 168,  114,  116,   95,  104,   76,   70,   36,   67,  104,
          48,   22,   69,   83,  141,  116,  116,  264,   91,  101,
         150,   74,   80,   66,  361,  258,  124,  163,  172,   30,
          61,   60,  166,   68,   93,   57,  131,  160,   71,   45,
         195,  114,   68,   79,   22,  167,   82,   39,   56,  152,
         127,  288,   63,   77,   72,   70,   23,   70,  461,  197,
          46,   38,   68,   48,   71,  102,  234,   66,   77,   93,
          20,  146,   64,   60,   48,   36,  358,   36,   57,  299,
          68,   80,  222,   86,  100,  120,   68,   61,  274,  117,
          66,  115,  345,  158,   30,  147,  173,   73,  204,  114,
          42,   44,  110,   77,  102,   66,  322,   62,  109,  110,
          29,   55,   92,  194,   84,  287,  254,   78,  107,   17,
          59,  227,   98,   95,  247,  105,   67,  328,   70,  102,
          84,   35,  110,   22,  158,   88,   52,  378,   42,  206,
          46,   93,  125,  115

torch.Size([512])
tensor([ 177,   76,  117,  244,  119,   66,  117,   64,   30,   83,
          72,   79,  493,  133,   69,   86,  113,   36,   63,  125,
         103,   71,   62,   73,  285,   66,   88,   75,  336,  132,
          56,   68,   37,  206,  180,  112,  136,   24,  230,  160,
          70,  263,   34,   60,   64,  103,   33,   61,   67,  114,
          29,   89,   88,   85,   73,   65,   67,  201,   22,  350,
         138,  112,   37,   68,   62,  213,   56,   69,   59,   76,
          33,   90,  206,   75,  207,  108,  340,  225,   91,  113,
          55,   99,   98,   63,   56,   58,   58,  278,   27,  147,
          80,   58,  188,   30,  362,   69,   58,   67,   57,   79,
          61,  142,   24,   64,   19,  148,  175,   56,   87,   62,
         159,  123,   55,  137,  409,  126,   48,   78,   79,  303,
          70,  109,  268,   66,   99,   27,  202,  131,   29,  122,
         247,   78,  126,   60,  202,  117,   83,  357,   82,   54,
          81,   69,   75,   59

torch.Size([512])
tensor([  75,  109,  150,   92,   93,  170,   92,  134,   87,  219,
          93,   64,  104,   75,  126,  331,   64,  261,   73,   30,
         103,   59,   76,   83,  208,  177,   71,   70,  131,   63,
          41,   21,  143,   74,  173,   71,   54,  124,   60,  245,
          98,   84,  101,  111,  168,   72,  143,   70,  341,  189,
         319,  256,  276,   93,   48,  204,  125,   67,  296,   88,
          57,  115,   70,   42,   72,  223,  168,   78,  169,  192,
         228,   80,   74,   26,   30,   79,   72,  159,   66,  215,
          71,   43,   87,   86,   81,   37,   98,   58,   60,   79,
         254,  205,   40,  208,  226,   64,  110,  123,  446,  395,
          36,   52,  318,  201,   93,  199,  171,  500,   63,   83,
          88,  319,  500,  333,   87,  172,  223,  234,  264,  234,
          63,  241,  246,  179,   90,   94,  204,   90,   66,  116,
         356,  105,  253,   69,   85,  111,   89,   28,   58,  189,
         189,  185,   89,  111


2020-07-02 16:51:45 Uploading - Uploading generated training modeltorch.Size([512])
tensor([ 168,  369,   55,   61,   57,   69,   84,   69,  105,  212,
          86,   65,  122,  313,  172,   72,   60,   47,   52,   77,
         329,   60,  127,   94,   63,  189,   69,   61,  168,   61,
         102,   86,  126,  103,  129,  207,   38,   33,   84,  336,
         102,  350,  103,   95,   83,   82,   82,   51,   48,  499,
          91,  122,  266,  161,   74,  186,  109,   59,  279,  263,
         254,   66,  185,   90,  129,  379,  213,   58,   43,   57,
          61,  122,  171,  150,   44,   49,   79,   57,  136,  108,
          88,  201,   82,   36,   92,   26,   70,   92,  311,  123,
         125,  252,  355,   38,   30,  235,  357,   64,  174,   81,
         130,   76,   74,   72,  132,  342,  450,  217,  132,   33,
          20,   57,   59,  128,   57,   89,   42,   21,   40,   27,
         123,  127,  203,   76,   29,   62,  143,  222,  268,   62,
          65,   71,  235,   64,

tensor([  78,  151,   74,   38,  142,  200,  137,  118,   93,   85,
         106,  211,  275,  113,   79,   89,   67,  138,  234,  169,
         162,   97,   91,   89,   56,   74,   64,   91,   73,   54,
         111,   72,   87,   56,   65,  103,  138,  149,  119,  187,
          53,   27,   63,  121,  114,  141,   66,  402,   65,  191,
          41,  250,  189,  103,  363,   61,   74,  133,   54,  118,
          58,  152,   61,   47,   34,   67,   57,   95,   35,  267,
         282,   71,  213,   54,   75,   83,   90,  109,  108,  341,
          75,   85,   30,  181,  188,  144,  126,   80,   73,  116,
          97,   82,  227,  111,  185,  165,   58,  284,  128,  114,
         321,   33,  134,   89,  140,   70,   60,   91,   60,   84,
         385,   49,   57,   98,  268,   26,  227,  156,   68,   81,
          83,   67,  251,   55,   66,  132,   74,  232,   71,   64,
         204,   90,   96,  134,   31,   69,  190,   28,   97,   71,
          66,  440,  113,   21,   88,  490,  142


2020-07-02 16:51:52 Completed - Training job completed
Training seconds: 286
Billable seconds: 286


## Step 5: Testing the model

As mentioned at the top of this notebook, we will be testing this model by first deploying it and then sending the testing data to the deployed endpoint. We will do this so that we can make sure that the deployed model is working correctly.

## Step 6: Deploy the model for testing

Now that we have trained our model, we would like to test it to see how it performs. Currently our model takes input of the form `review_length, review[500]` where `review[500]` is a sequence of `500` integers which describe the words present in the review, encoded using `word_dict`. Fortunately for us, SageMaker provides built-in inference code for models with simple inputs such as this.

There is one thing that we need to provide, however, and that is a function which loads the saved model. This function must be called `model_fn()` and takes as its only parameter a path to the directory where the model artifacts are stored. This function must also be present in the python file which we specified as the entry point. In our case the model loading function has been provided and so no changes need to be made.

**NOTE**: When the built-in inference code is run it must import the `model_fn()` method from the `train.py` file. This is why the training code is wrapped in a main guard ( ie, `if __name__ == '__main__':` )

Since we don't need to change anything in the code that was uploaded during training, we can simply deploy the current model as-is.

**NOTE:** When deploying a model you are asking SageMaker to launch an compute instance that will wait for data to be sent to it. As a result, this compute instance will continue to run until *you* shut it down. This is important to know since the cost of a deployed endpoint depends on how long it has been running for.

In other words **If you are no longer using a deployed endpoint, shut it down!**

**TODO:** Deploy the trained model.

In [188]:
# TODO: Deploy the trained model                                         
predictor = estimator.deploy(initial_instance_count = 1, instance_type = 'ml.m4.xlarge')    # ml.m4.xlarge 

Parameter image will be renamed to image_uri in SageMaker Python SDK v2.
'create_image_uri' will be deprecated in favor of 'ImageURIProvider' class in SageMaker Python SDK v2.


---------------!

## Step 7 - Use the model for testing

Once deployed, we can read in the test data and send it off to our deployed model to get some results. Once we collect all of the results we can determine how accurate our model is.

In [189]:
test_X = pd.concat([pd.DataFrame(test_X_len), pd.DataFrame(test_X)], axis=1)

In [190]:
# We split the data into chunks and send each chunk seperately, accumulating the results.

def predict(data, rows=512):
    split_array = np.array_split(data, int(data.shape[0] / float(rows) + 1))
    predictions = np.array([])
    for array in split_array:
        predictions = np.append(predictions, predictor.predict(array))
    
    return predictions

In [191]:
predictions = predict(test_X.values)
predictions = [round(num) for num in predictions]

In [192]:
from sklearn.metrics import accuracy_score
accuracy_score(test_y, predictions)

0.8578

**Question:** How does this model compare to the XGBoost model you created earlier? Why might these two models perform differently on this dataset? Which do *you* think is better for sentiment analysis?

**Answer:**
It's worse due to low epochs.

### (TODO) More testing

We now have a trained model which has been deployed and which we can send processed reviews to and which returns the predicted sentiment. However, ultimately we would like to be able to send our model an unprocessed review. That is, we would like to send the review itself as a string. For example, suppose we wish to send the following review to our model.

In [196]:
test_review = 'The simplest pleasures in life are the best, and this film is one of them. Combining a rather basic storyline of love and adventure this movie transcends the usual weekend fair with wit and unmitigated charm.'

The question we now need to answer is, how do we send this review to our model?

Recall in the first section of this notebook we did a bunch of data processing to the IMDb dataset. In particular, we did two specific things to the provided reviews.
 - Removed any html tags and stemmed the input
 - Encoded the review as a sequence of integers using `word_dict`
 
In order process the review we will need to repeat these two steps.

**TODO**: Using the `review_to_words` and `convert_and_pad` methods from section one, convert `test_review` into a numpy array `test_data` suitable to send to our model. Remember that our model expects input of the form `review_length, review[500]`.

In [197]:
# TODO: Convert test_review into a form usable by the model and save the results in test_data
test_words = review_to_words(test_review)

test_data, leng = convert_and_pad(word_dict, test_words)  # sentence, leng, pad
test_data = np.array([np.array([leng] + test_data)])



Now that we have processed the review, we can send the resulting array to our model to predict the sentiment of the review.

In [195]:
predictor.predict(test_data)

array(0.94588804, dtype=float32)

Since the return value of our model is close to `1`, we can be certain that the review we submitted is positive.

### Delete the endpoint

Of course, just like in the XGBoost notebook, once we've deployed an endpoint it continues to run until we tell it to shut down. Since we are done using our endpoint for now, we can delete it.

In [217]:
estimator.delete_endpoint()

ClientError: An error occurred (ValidationException) when calling the DeleteEndpoint operation: Could not find endpoint "arn:aws:sagemaker:ap-northeast-2:702264002183:endpoint/sagemaker-pytorch-2020-07-02-16-44-40-954".

## Step 6 (again) - Deploy the model for the web app

Now that we know that our model is working, it's time to create some custom inference code so that we can send the model a review which has not been processed and have it determine the sentiment of the review.

As we saw above, by default the estimator which we created, when deployed, will use the entry script and directory which we provided when creating the model. However, since we now wish to accept a string as input and our model expects a processed review, we need to write some custom inference code.

We will store the code that we write in the `serve` directory. Provided in this directory is the `model.py` file that we used to construct our model, a `utils.py` file which contains the `review_to_words` and `convert_and_pad` pre-processing functions which we used during the initial data processing, and `predict.py`, the file which will contain our custom inference code. Note also that `requirements.txt` is present which will tell SageMaker what Python libraries are required by our custom inference code.

When deploying a PyTorch model in SageMaker, you are expected to provide four functions which the SageMaker inference container will use.
 - `model_fn`: This function is the same function that we used in the training script and it tells SageMaker how to load our model.
 - `input_fn`: This function receives the raw serialized input that has been sent to the model's endpoint and its job is to de-serialize and make the input available for the inference code.
 - `output_fn`: This function takes the output of the inference code and its job is to serialize this output and return it to the caller of the model's endpoint.
 - `predict_fn`: The heart of the inference script, this is where the actual prediction is done and is the function which you will need to complete.

For the simple website that we are constructing during this project, the `input_fn` and `output_fn` methods are relatively straightforward. We only require being able to accept a string as input and we expect to return a single value as output. You might imagine though that in a more complex application the input or output may be image data or some other binary data which would require some effort to serialize.

### (TODO) Writing inference code

Before writing our custom inference code, we will begin by taking a look at the code which has been provided.

In [216]:
!pygmentize serve/predict.py

import argparse
import json
import os
import pickle
import sys
import sagemaker_containers
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torch.utils.data

from model import LSTMClassifier

from utils import review_to_words, convert_and_pad

def model_fn(model_dir):
    """Load the PyTorch model from the `model_dir` directory."""
    print("Loading model.")

    # First, load the parameters used to create the model.
    model_info = {}
    model_info_path = os.path.join(model_dir, 'model_info.pth')
    with open(model_info_path, 'rb') as f:
        model_info = torch.load(f)

    print("model_info: {}".format(model_info))

    # Determine the device and construct the model.
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = LSTMClassifier(model_info['embedding_dim'], model_info['hidden_dim'], model_info['vocab_size'])

    # Load the store model parameters.
    model_path = os.path.join(mod

As mentioned earlier, the `model_fn` method is the same as the one provided in the training code and the `input_fn` and `output_fn` methods are very simple and your task will be to complete the `predict_fn` method. Make sure that you save the completed file as `predict.py` in the `serve` directory.

**TODO**: Complete the `predict_fn()` method in the `serve/predict.py` file.

### Deploying the model

Now that the custom inference code has been written, we will create and deploy our model. To begin with, we need to construct a new PyTorchModel object which points to the model artifacts created during training and also points to the inference code that we wish to use. Then we can call the deploy method to launch the deployment container.

**NOTE**: The default behaviour for a deployed PyTorch model is to assume that any input passed to the predictor is a `numpy` array. In our case we want to send a string so we need to construct a simple wrapper around the `RealTimePredictor` class to accomodate simple strings. In a more complicated situation you may want to provide a serialization object, for example if you wanted to sent image data.

In [219]:
from sagemaker.predictor import RealTimePredictor
from sagemaker.pytorch import PyTorchModel

class StringPredictor(RealTimePredictor):
    def __init__(self, endpoint_name, sagemaker_session):
        super(StringPredictor, self).__init__(endpoint_name, sagemaker_session, content_type='text/plain')

model = PyTorchModel(model_data=estimator.model_data,
                     role = role,
                     framework_version='0.4.0',
                     entry_point='predict.py',
                     source_dir='serve',
                     predictor_cls=StringPredictor)

predictor = model.deploy(initial_instance_count=1, instance_type='ml.m4.xlarge')

Parameter image will be renamed to image_uri in SageMaker Python SDK v2.
'create_image_uri' will be deprecated in favor of 'ImageURIProvider' class in SageMaker Python SDK v2.


-----------------!

### Testing the model

Now that we have deployed our model with the custom inference code, we should test to see if everything is working. Here we test our model by loading the first `250` positive and negative reviews and send them to the endpoint, then collect the results. The reason for only sending some of the data is that the amount of time it takes for our model to process the input and then perform inference is quite long and so testing the entire data set would be prohibitive.

In [220]:
import glob

def test_reviews(data_dir='../data/aclImdb', stop=250):
    
    results = []
    ground = []
    
    # We make sure to test both positive and negative reviews    
    for sentiment in ['pos', 'neg']:
        
        path = os.path.join(data_dir, 'test', sentiment, '*.txt')
        files = glob.glob(path)
        
        files_read = 0
        
        print('Starting ', sentiment, ' files')
        
        # Iterate through the files and send them to the predictor
        for f in files:
            with open(f) as review:
                # First, we store the ground truth (was the review positive or negative)
                if sentiment == 'pos':
                    ground.append(1)
                else:
                    ground.append(0)
                # Read in the review and convert to 'utf-8' for transmission via HTTP
                review_input = review.read().encode('utf-8')
                # Send the review to the predictor and store the results
                results.append(int(predictor.predict(review_input)))
                
            # Sending reviews to our endpoint one at a time takes a while so we
            # only send a small number of reviews
            files_read += 1
            if files_read == stop:
                break
            
    return ground, results

In [221]:
predictor.predict(test_review)

b'1'

In [222]:
ground, results = test_reviews()

Starting  pos  files
Starting  neg  files


In [223]:
from sklearn.metrics import accuracy_score
accuracy_score(ground, results)

0.844

As an additional test, we can try sending the `test_review` that we looked at earlier.

In [224]:
predictor.predict(test_review)

b'1'

Now that we know our endpoint is working as expected, we can set up the web page that will interact with it. If you don't have time to finish the project now, make sure to skip down to the end of this notebook and shut down your endpoint. You can deploy it again when you come back.

## Step 7 (again): Use the model for the web app

> **TODO:** This entire section and the next contain tasks for you to complete, mostly using the AWS console.

So far we have been accessing our model endpoint by constructing a predictor object which uses the endpoint and then just using the predictor object to perform inference. What if we wanted to create a web app which accessed our model? The way things are set up currently makes that not possible since in order to access a SageMaker endpoint the app would first have to authenticate with AWS using an IAM role which included access to SageMaker endpoints. However, there is an easier way! We just need to use some additional AWS services.

<img src="Web App Diagram.svg">

The diagram above gives an overview of how the various services will work together. On the far right is the model which we trained above and which is deployed using SageMaker. On the far left is our web app that collects a user's movie review, sends it off and expects a positive or negative sentiment in return.

In the middle is where some of the magic happens. We will construct a Lambda function, which you can think of as a straightforward Python function that can be executed whenever a specified event occurs. We will give this function permission to send and recieve data from a SageMaker endpoint.

Lastly, the method we will use to execute the Lambda function is a new endpoint that we will create using API Gateway. This endpoint will be a url that listens for data to be sent to it. Once it gets some data it will pass that data on to the Lambda function and then return whatever the Lambda function returns. Essentially it will act as an interface that lets our web app communicate with the Lambda function.

### Setting up a Lambda function

The first thing we are going to do is set up a Lambda function. This Lambda function will be executed whenever our public API has data sent to it. When it is executed it will receive the data, perform any sort of processing that is required, send the data (the review) to the SageMaker endpoint we've created and then return the result.

#### Part A: Create an IAM Role for the Lambda function

Since we want the Lambda function to call a SageMaker endpoint, we need to make sure that it has permission to do so. To do this, we will construct a role that we can later give the Lambda function.

Using the AWS Console, navigate to the **IAM** page and click on **Roles**. Then, click on **Create role**. Make sure that the **AWS service** is the type of trusted entity selected and choose **Lambda** as the service that will use this role, then click **Next: Permissions**.

In the search box type `sagemaker` and select the check box next to the **AmazonSageMakerFullAccess** policy. Then, click on **Next: Review**.

Lastly, give this role a name. Make sure you use a name that you will remember later on, for example `LambdaSageMakerRole`. Then, click on **Create role**.

#### Part B: Create a Lambda function

Now it is time to actually create the Lambda function.

Using the AWS Console, navigate to the AWS Lambda page and click on **Create a function**. When you get to the next page, make sure that **Author from scratch** is selected. Now, name your Lambda function, using a name that you will remember later on, for example `sentiment_analysis_func`. Make sure that the **Python 3.6** runtime is selected and then choose the role that you created in the previous part. Then, click on **Create Function**.

On the next page you will see some information about the Lambda function you've just created. If you scroll down you should see an editor in which you can write the code that will be executed when your Lambda function is triggered. In our example, we will use the code below. 

```python
# We need to use the low-level library to interact with SageMaker since the SageMaker API
# is not available natively through Lambda.
import boto3

def lambda_handler(event, context):

    # The SageMaker runtime is what allows us to invoke the endpoint that we've created.
    runtime = boto3.Session().client('sagemaker-runtime')

    # Now we use the SageMaker runtime to invoke our endpoint, sending the review we were given
    response = runtime.invoke_endpoint(EndpointName = '**ENDPOINT NAME HERE**',    # The name of the endpoint we created
                                       ContentType = 'text/plain',                 # The data format that is expected
                                       Body = event['body'])                       # The actual review

    # The response is an HTTP response whose body contains the result of our inference
    result = response['Body'].read().decode('utf-8')

    return {
        'statusCode' : 200,
        'headers' : { 'Content-Type' : 'text/plain', 'Access-Control-Allow-Origin' : '*' },
        'body' : result
    }
```

Once you have copy and pasted the code above into the Lambda code editor, replace the `**ENDPOINT NAME HERE**` portion with the name of the endpoint that we deployed earlier. You can determine the name of the endpoint using the code cell below.

In [225]:
predictor.endpoint

'sagemaker-pytorch-2020-07-02-18-27-04-595'

Once you have added the endpoint name to the Lambda function, click on **Save**. Your Lambda function is now up and running. Next we need to create a way for our web app to execute the Lambda function.

### Setting up API Gateway

Now that our Lambda function is set up, it is time to create a new API using API Gateway that will trigger the Lambda function we have just created.

Using AWS Console, navigate to **Amazon API Gateway** and then click on **Get started**.

On the next page, make sure that **New API** is selected and give the new api a name, for example, `sentiment_analysis_api`. Then, click on **Create API**.

Now we have created an API, however it doesn't currently do anything. What we want it to do is to trigger the Lambda function that we created earlier.

Select the **Actions** dropdown menu and click **Create Method**. A new blank method will be created, select its dropdown menu and select **POST**, then click on the check mark beside it.

For the integration point, make sure that **Lambda Function** is selected and click on the **Use Lambda Proxy integration**. This option makes sure that the data that is sent to the API is then sent directly to the Lambda function with no processing. It also means that the return value must be a proper response object as it will also not be processed by API Gateway.

Type the name of the Lambda function you created earlier into the **Lambda Function** text entry box and then click on **Save**. Click on **OK** in the pop-up box that then appears, giving permission to API Gateway to invoke the Lambda function you created.

The last step in creating the API Gateway is to select the **Actions** dropdown and click on **Deploy API**. You will need to create a new Deployment stage and name it anything you like, for example `prod`.

You have now successfully set up a public API to access your SageMaker model. Make sure to copy or write down the URL provided to invoke your newly created public API as this will be needed in the next step. This URL can be found at the top of the page, highlighted in blue next to the text **Invoke URL**.

## Step 4: Deploying our web app

Now that we have a publicly available API, we can start using it in a web app. For our purposes, we have provided a simple static html file which can make use of the public api you created earlier.

In the `website` folder there should be a file called `index.html`. Download the file to your computer and open that file up in a text editor of your choice. There should be a line which contains **\*\*REPLACE WITH PUBLIC API URL\*\***. Replace this string with the url that you wrote down in the last step and then save the file.

Now, if you open `index.html` on your local computer, your browser will behave as a local web server and you can use the provided site to interact with your SageMaker model.

If you'd like to go further, you can host this html file anywhere you'd like, for example using github or hosting a static site on Amazon's S3. Once you have done this you can share the link with anyone you'd like and have them play with it too!

> **Important Note** In order for the web app to communicate with the SageMaker endpoint, the endpoint has to actually be deployed and running. This means that you are paying for it. Make sure that the endpoint is running when you want to use the web app but that you shut it down when you don't need it, otherwise you will end up with a surprisingly large AWS bill.

**TODO:** Make sure that you include the edited `index.html` file in your project submission.

Now that your web app is working, trying playing around with it and see how well it works.

**Question**: Give an example of a review that you entered into your web app. What was the predicted sentiment of your example review?

### Delete the endpoint

Remember to always shut down your endpoint if you are no longer using it. You are charged for the length of time that the endpoint is running so if you forget and leave it on you could end up with an unexpectedly large bill.

In [226]:
predictor.delete_endpoint()